CREATE USER 'newuser'@'localhost' IDENTIFIED BY 'password';
CREATE ALL PRIVILEGES ON *.* TO 'newuser'@'localhost' IDENTIFIED BY “password”;
FLUSH PRIVILEGES;
CREATE DATABASE users;
USE users;
CREATE TABLE us_db (id INT NOT NULL AUTO_INCREMENT, login VARCHAR(20), hash VARCHAR(50),PRIMARY KEY (id));
CREATE TABLE art_db (id INT NOT NULL AUTO_INCREMENT, name VARCHAR(20), descr VARCHAR(200),  pic VARCHAR(200), art VARCHAR(20), owner INT, FOREIGN KEY(owner) REFERENCES us_db(id),PRIMARY KEY (id));
